version: 2
jobs:
  build-and-commit:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.727-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:34:9d:06:d9:29:cb:ca:f7:37:49:09:6b:df:29:0a"
      - checkout
      - run: clojure -R:default-deps
      - run: clojure -M:test
      - run: sudo npm install -g shadow-cljs
      - run: npm install
      - run: shadow-cljs release frontend
      - run: mv -f resources/public/js/main.js main.js.bak
      - run: mv -f resources/public/index.html index.html.bak
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "jherrlin@gmail.com"
            git config user.name "CircleCI Job"
            git fetch --all
            rm -f package-lock.json
            git checkout gh-pages
            mkdir -p js
            mv -f main.js.bak js/main.js
            mv -f index.html.bak index.html
            git add js/main.js index.html
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push -f origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-commit:
          filters:
            branches:
              only: master
