version: 2
jobs:
  build-and-commit:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.727-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - checkout
      - run: sudo npm install -g shadow-cljs
      - run: npm install
      - run: shadow-cljs release frontend
      - run: cp
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "jherrlin@gmail.com"
            git config user.name "CircleCI Job"
            git checkout master
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push origin master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-commit
