version: 2
jobs:
  build-and-commit:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.727-node-browsers

    environment:
      JVM_OPTS: -Xmx3200m
      TZ: "Europe/Stockholm"

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6a:34:9d:06:d9:29:cb:ca:f7:37:49:09:6b:df:29:0a"
      - checkout
      - run: sudo npm install -g shadow-cljs
      - run: npm install
      - run: shadow-cljs release frontend
      - run: mkdir -p js
      - run: mv -f resources/public/js/main.js js/
      - run: mv -f resources/public/index.html .
      - run: ls -lha
      - run:
          name: Commit to GitHub
          command: |
            git config user.email "jherrlin@gmail.com"
            git config user.name "CircleCI Job"
            git fetch --all
            git checkout gh-pages
            git add js/main.js index.html
            git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
            git push -f origin gh-pages

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-and-commit
